-- 코드를 입력하세요
WITH CANNOT_RENT AS (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
    DATE_FORMAT(START_DATE, '%Y-%m') = '2022-11' OR 
    DATE_FORMAT(END_DATE, '%Y-%m') = '2022-11' OR 
    (START_DATE < '2022-11-01' AND END_DATE >= '2022-12-01')
),
DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, C.CAR_TYPE,
ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN DISCOUNT D ON C.CAR_TYPE = D.CAR_TYPE
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CANNOT_RENT)
HAVING FEE >= 500000 AND FEE < 2000000