-- 코드를 작성해주세요
WITH ECOLI_Q AS (
    SELECT ID, CASE
    WHEN MONTH(DIFFERENTIATION_DATE) <= '3' THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) <= '6' THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) <= '9' THEN '3Q'
    ELSE '4Q'
    END QUARTER
    FROM ECOLI_DATA
)
SELECT QUARTER, COUNT(*) ECOLI_COUNT
FROM ECOLI_Q
GROUP BY QUARTER
ORDER BY QUARTER