WITH YEAR_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT Y.YEAR, (MAX_SIZE - SIZE_OF_COLONY) YEAR_DEV, ID 
FROM ECOLI_DATA E JOIN YEAR_SIZE Y ON YEAR(E.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY Y.YEAR, YEAR_DEV