-- 코드를 작성해주세요
SELECT ID, CASE
WHEN RK * 100 / CNT <= 25 THEN 'CRITICAL'
WHEN RK * 100 / CNT <= 50 THEN 'HIGH'
WHEN RK * 100 / CNT <= 75 THEN 'MEDIUM'
ELSE 'LOW'
END COLONY_NAME
FROM (
    SELECT ID, rank() over (ORDER BY SIZE_OF_COLONY DESC) RK, COUNT(*) over () CNT
    FROM ECOLI_DATA
) RANK_DATE
ORDER BY ID
