WITH RECURSIVE ECOLI_GENE AS (
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT D.ID, D.PARENT_ID, GENERATION + 1 GENERATION
    FROM ECOLI_DATA D JOIN ECOLI_GENE G ON G.ID = D.PARENT_ID
) 
SELECT COUNT(*) COUNT, G1.GENERATION
FROM ECOLI_GENE G1 LEFT JOIN ECOLI_GENE G2 ON G1.ID = G2.PARENT_ID
WHERE G2.ID IS NULL
GROUP BY G1.GENERATION
ORDER BY G1.GENERATION