-- 코드를 작성해주세요
WITH EMP_GRADE AS (
    SELECT E.EMP_NO, EMP_NAME, SAL, CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END GRADE
    FROM HR_EMPLOYEES E JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
    GROUP BY EMP_NO
)
SELECT EMP_NO, EMP_NAME, GRADE, CASE
WHEN GRADE = 'S' THEN SAL * 20 / 100
WHEN GRADE = 'A' THEN SAL * 15 / 100
WHEN GRADE = 'B' THEN SAL * 10 / 100
ELSE 0
END BONUS
FROM EMP_GRADE
ORDER BY EMP_NO