-- 코드를 입력하세요
WITH MX_REVIEW AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE P 
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
JOIN MX_REVIEW M ON M.MEMBER_ID = P.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
