SELECT I1.ITEM_ID, I1.ITEM_NAME, I1.RARITY
FROM ITEM_INFO I1 JOIN ITEM_TREE T ON I1.ITEM_ID = T.ITEM_ID
JOIN ITEM_INFO I2 ON I2.ITEM_ID = T.PARENT_ITEM_ID
WHERE I2.RARITY = 'RARE'
ORDER BY I1.ITEM_ID DESC
