-- 코드를 작성해주세요
WITH HR_SCORE AS (
    SELECT G1.EMP_NO, G1.YEAR, G1.SCORE + G2.SCORE SCORE
    FROM HR_GRADE G1 JOIN HR_GRADE G2 ON G1.EMP_NO = G2.EMP_NO AND G1.HALF_YEAR != G2.HALF_YEAR
)
SELECT DISTINCT SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
JOIN HR_SCORE S ON S.EMP_NO = E.EMP_NO
WHERE YEAR = 2022 AND SCORE = (
    SELECT MAX(SCORE)
    FROM HR_SCORE
    WHERE YEAR = 2022
)