-- 코드를 작성해주세요
WITH FISH_LENGTH AS (
    SELECT FISH_TYPE, AVG(LENGTH) AVG_LENGTH
    FROM (
        SELECT FISH_TYPE, IFNULL(LENGTH, 10) LENGTH
        FROM FISH_INFO
    ) FISH
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) >= 33
)
SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, I.FISH_TYPE
FROM FISH_INFO I JOIN FISH_LENGTH L ON I.FISH_TYPE = L.FISH_TYPE
GROUP BY I.FISH_TYPE
ORDER BY FISH_TYPE